### ISSUE TITLE
No CoC on repository

### ISSUE THREAD

**Issue by brendanzab** [wilbowma/pl-thesaurus#3]
Might be handy for attracting new contributors!

**Comment by aatxe** [comment]
The [Contributor Covenant](https://www.contributor-covenant.org/) is a popular choice. I'm also a fan of the [FreeBSD Code of Conduct](https://www.freebsd.org/internal/code-of-conduct.html). There is, of course, also the [ACM Code of Ethics and Professional Conduct](https://www.acm.org/about-acm/acm-code-of-ethics-and-professional-conduct).
